import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import  { Toaster } from 'react-hot-toast';
import AuthProvider from "@/providers/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-100 ${inter.className}`}>
         <AuthProvider>
            <Toaster />
            {children}
         </AuthProvider>
      </body>
    </html>
  );
}
